# Generated by Django 4.2.6 on 2023-10-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='college',
            field=models.CharField(choices=[('PU', 'Princeton')], default='PU', max_length=5),
        ),
    ]
