# Generated by Django 4.2.6 on 2023-12-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='college',
            field=models.CharField(choices=[('PU', 'Princeton University')], default='PU', max_length=5),
        ),
    ]
