# Generated by Django 4.2.6 on 2023-10-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='trip',
            name='college',
            field=models.CharField(default='PU', max_length=5),
            preserve_default=False,
        ),
    ]
