# Generated by Django 4.2.6 on 2023-11-06 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_remove_location_postal_code_trip_college"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="location",
            name="longitude",
        ),
        migrations.AddField(
            model_name="location",
            name="postal_code",
            field=models.CharField(default="00000", max_length=5),
        ),
        migrations.AlterField(
            model_name="triprequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
