# Generated by Django 4.2.6 on 2023-11-12 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_departure_time_triprequest_max_departure_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triprequest',
            old_name='min_departure_time',
            new_name='earliest_departure_time',
        ),
        migrations.RenameField(
            model_name='triprequest',
            old_name='max_departure_time',
            new_name='latest_departure_time',
        ),
    ]
