# Generated by Django 4.2.6 on 2023-11-14 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_trip_join_requests_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="joinrequest",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="join_requests",
                to="api.trip",
            ),
        ),
    ]
