# Generated by Django 4.2.6 on 2023-11-24 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0008_alter_confirmationrequest_join_request_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="participant_list",
            field=models.ManyToManyField(
                blank=True, related_name="trips", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
