# Generated by Django 4.2.6 on 2023-11-24 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0009_alter_trip_participant_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joinrequest",
            name="participants_that_accepted",
            field=models.ManyToManyField(
                blank=True, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="blacklisted_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="blacklisted_trips",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
