# Generated by Django 4.2.6 on 2023-11-29 01:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='departure_time',
            new_name='earliest_departure_time',
        ),
        migrations.AddField(
            model_name='trip',
            name='latest_departure_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 20, 39, 30, 226483)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TripUserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earliest_departure_time', models.DateTimeField()),
                ('latest_departure_time', models.DateTimeField()),
                ('num_luggage_bags', models.IntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_timespans', to='api.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_timespans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
