# Generated by Django 4.2.6 on 2023-11-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_departure_time_trip_earliest_departure_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(default='00000', max_length=12),
        ),
    ]
