# Generated by Django 4.2.6 on 2023-12-12 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_confirmationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='num_join_requests',
        ),
    ]
