# Generated by Django 5.0 on 2023-12-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_location_postal_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triprequest',
            name='arrival_location',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='departure_location',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='earliest_departure_time',
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='latest_departure_time',
        ),
        migrations.RemoveField(
            model_name='tripuserdetails',
            name='earliest_departure_time',
        ),
        migrations.RemoveField(
            model_name='tripuserdetails',
            name='latest_departure_time',
        ),
        migrations.AddField(
            model_name='triprequest',
            name='trip_nickname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tripuserdetails',
            name='trip_nickname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
