# Generated by Django 5.0 on 2023-12-13 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_triprequest_arrival_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripuserdetails',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_user_details', to='api.trip'),
        ),
        migrations.AlterField(
            model_name='tripuserdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_user_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
