# Generated by Django 4.2.6 on 2023-10-30 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SingleTripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_members_accepted', models.IntegerField()),
                ('trip_details_changed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('num_participants', models.IntegerField()),
                ('is_full', models.BooleanField()),
                ('associated_college', models.CharField(max_length=255)),
                ('depature_time', models.DateTimeField()),
                ('num_luggage_bags', models.IntegerField()),
                ('num_trip_requests', models.IntegerField()),
                ('arrival_location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='api.location')),
                ('blacklisted_users', models.ManyToManyField(related_name='blacklisted_trips', to=settings.AUTH_USER_MODEL)),
                ('departure_location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='api.location')),
                ('participant_list', models.ManyToManyField(related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('trip_requests', models.ManyToManyField(related_name='trip_requested', to='api.singletriprequest')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='MulipleTripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('departure_time', models.DateTimeField()),
                ('num_luggage_bags', models.IntegerField()),
                ('arrival_location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='api.location')),
                ('departure_location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='api.location')),
                ('trips_requested', models.ManyToManyField(related_name='parent_trip_request', to='api.singletriprequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('trip_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.singletriprequest')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
