# Generated by Django 4.2.6 on 2023-10-31 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_singletriprequest_joinrequest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='depature_time',
            new_name='departure_time',
        ),
        migrations.RenameField(
            model_name='triprequest',
            old_name='trips_requested',
            new_name='join_requests',
        ),
    ]
