# Generated by Django 4.2.6 on 2023-10-31 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_trip_request_confirmationrequest_join_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='associated_college',
        ),
    ]
