name: Scheduled jobs on a CRON schedule

on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Delete old trips and trip requests
        python manage.py delete_old_trips