name: Scheduled jobs on a CRON schedule
on: [push]
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Delete old trips and trip requests
        run: python manage.py delete_old_trips